### ISSUE TITLE
Lesson 08 

### ISSUE THREAD

**Issue by anton-koshevyi** [YevheniySerhiyenko/geekhub8#11]
#### Task 1
- [x] `CollectionOperationsImpl::fill` - update loop bounds to remove extra check
- [x] `CollectionOperationsImpl::max` - test case where passed collection is empty
- [x] `CollectionOperationsImpl::min` - test case where passed collection is empty
- [x] `CollectionOperationsImpl::reduce` - [method implementations is wrong](https://www.baeldung.com/java-stream-reduce)
- [x] `CollectionOperationsImpl::groupBy` - do not update map members by reference
- [x] `CollectionOperationsImpl::toMap` - test case where passed collection is empty
- [x] `CollectionOperationsImpl::toMap` - do not update map members by reference
- [x] `Car.class`, `Color.class`, `*Comparator.class` - move test fixtures to `test` source-set
- [x] `CollectionOperationsImplTest.class` - use plain jdk classes as test fixtures instead of custom
- [x] `CollectionOperationsImplTest.class` - test methods using more forms of implementation of fuctional interfaces
