### ISSUE TITLE
Lesson 09

### ISSUE THREAD

**Issue by anton-koshevyi** [YevheniySerhiyenko/geekhub8#12]
#### Task 1
- [ ] `CollectionOperationsImpl.class` - reformat code: invoke one functional method per line 

#### Common
- [ ] Apply remarks from previous issues
- [ ] Do not change previous lessons
