### ISSUE TITLE
Lesson 04

### ISSUE THREAD

**Issue by anton-koshevyi** [YevheniySerhiyenko/geekhub8#2]
#### Task 2
- [x] `AuthenticationService.class` - field can be final
- [x] `AuthenticationService::auth` - provide message when throwing exceptions
- [x] `AuthenticationService::auth` - use Guard Clause to avoid extra branching
- [x] `AuthenticationService::isEmpty` - method can be static 
- [x] `UserNotFoundException.class` - errors should not be used in application logic
- [x] `InMemoryUserSource.class` - optimize imports
- [x] `User.class` - fields can be final

#### Common
- [x] Rollback changes in Lesson 5
