### ISSUE TITLE
Lesson 05

### ISSUE THREAD

**Issue by anton-koshevyi** [YevheniySerhiyenko/geekhub8#5]
#### Task 1
- [x] `Car.class` - there are no need to implement `Comparable`
- [x] `Color.class` - order members by access modifier
- [x] `Color.class` - there are no need to implement `Comparable`

---

#### Task 1
- [x] `Color.class` - `colorMax` follow naming conventions
- [x] `Color::checkColorRange` - `-1` is not valid color value

---

#### Task 1
- [x] `Color::new` - extract color validation to reusable method
- [x] `Color::new` - move magic numbers into constants

#### Task 3
- [x] `VotingBox::iterator` - remove delegating to collection
- [x] `VotingBox::add` - use variable to avoid multiple invocation of same method
- [x] `VotingBox::remove` - method is too complex, simplify by manual iteration
- [x] `VotingBox::containsAll` - method can be simplified
- [x] `VotingBox::addAll` - `array` variable can be omitted
- [x] `VotingBox::removeAll` - method can be simplified
- [x] `VotingBox::retainAll` - method can be simplified

#### Common
- [x] Reformat code
- [x] Do not comment/uncomment another lesson-modules in `settings.gradle`

#### Recomendations
- Follow [Git commit message guidelines](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)
- Choose codestyle and setup IDE according to it. Recomended style conventions:
  - [Google](https://google.github.io/styleguide/javaguide.html)
  - [Oracle](https://www.oracle.com/java/technologies/javase/codeconventions-contents.html)

---

#### Task 1
- [x] `Color.class` - implement validation according to task
- [x] `Color.class` - declare each field in own line
- [x] `Car.class` - `racer`, `carName` bad variable names. Note: factory param names should match with model field names

#### Task 2
- [x] `SetOperations::equals` - use `left` and `right` param names when perform operation with generic objects
- [x] `SetOperations::equals` - investigate `Objects` class to perform null-safe comparison
- [x] `SetOperationsImpl.class` - fields can be removed
- [x] `SetOperationsImpl::union` - `unmodSet2` field can be omitted

#### Task 3
- [x] `Vote.class` - `NUMBER_CANDIDATE` bad variable name, wrong format
- [x] `VotingBox.class` - use array to hold votes
- [x] `VotingBox::size` - method should return votes count without any calculation
- [x] `VotingBox::add` - `0`, `1` use named fields for candidate names instead of magic numbers
