### ISSUE TITLE
Lesson 06

### ISSUE THREAD

**Issue by anton-koshevyi** [YevheniySerhiyenko/geekhub8#9]
#### Task 2
- [ ] `TaskManagerImpl::getTasksForToday` - reuse existent method to get task for specific date
- [ ] `TaskManagerImpl::addTask` - there are no need to get tasks for date when no limit specified
- [ ] `TaskManagerImpl::getTasksByCategory` - `work` bad param name
- [ ] `TaskManagerImpl::getTasksByCategories` - value-list sorting is redunant according to reused method logic
- [ ] `TaskManagerImpl::removeTasks` - reuse existent method to get task for specific date
- [ ] `TaskManagerImpl::get*` - repeatable task is valid case and should not be excluded, e.g `code - eat - code`
- [ ] `TaskDateComparator::compare` - implement comparator in natural order, reverse locally when required

#### Common
- [ ] Apply remarks from previous lessons
- [ ] Reformat code

#### Recomendations
- Apply Singleton pattern to plain comparators
